removing compat default.nix to stimulate the flake
Chasing after a fix for this:
error: cannot fetch input
'path:../../?narHash=sha256-N9NTsNMmGPXJnOgI3FoWkAfwLkQx5fnG+aFRZCtlxZU='
because it uses a relative path

Only affects CI.  Guess I have to take a look at that narHash to see if this was
even the issue.